In [5]:
import numpy as np
import pyCalc as p
import random
l1 = p.var("function")
l1_error = p.var("function")
sig = p.var("function")
l1_delta = p.var("function")
hlp = p.var("function")
tmp = p.var("function")
xs = p.var("constant",np.array([  [0,1,0],
                [0,0,0],
                [0,0,1],
                [1,0,0] ], dtype= float))
ys = p.var("constant", np.array([1,0,1,0], dtype=float))
weights =np.array([[ 0.83655703],
 [ 0.91094098],
 [-0.43812108]])
ws = p.var("independent", np.array([1,3]))
l1.f(ws, xs, "*")
l1_error.f(ys, l1, "-")
sig.sf(l1, "sigmoid_r")
l1_delta.f(sig, l1_error, "*")
hlp.f(xs,l1_delta, "colwise")
tmp.sf(hlp, "rowsum")

In [6]:
print(weights)
print(tmp.value(weights).T)
for i in range(1000):
    weights = weights + tmp.value(weights)

print(weights)

[[ 0.83655703]
 [ 0.91094098]
 [-0.43812108]]
[[ 0.32286815 -0.12239681  0.34339559]]
[[ 0.01162259]
 [ 8.17239282]
 [-8.14359958]]
