In [4]:
import numpy as np

# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))
    
# input dataset
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])
    
# output dataset            
y = np.array([[0,0,1,1]]).T

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

# initialize weights randomly with mean 0
syn0 = np.array([[ 0.83655703],
 [ 0.91094098],
 [-0.43812108]], dtype = float)

for iter in range(1):

    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    print("l0")
    print(np.dot(l0,syn0))
    print("l1")
    print(l1)

    # how much did we miss?
    l1_error = y - l1
    print("l1_error")
    print(l1_error)
    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)
    print("sig")
    print(nonlin(l1,True))
    print("l1_delta")
    print(l1_delta)
    # update weights
    print("tmp")
    print(np.dot(l0.T,l1_delta))
    syn0 += np.dot(l0.T,l1_delta)

print ("Output After Training:")
print (l1)

print(syn0)


l0
[[-0.43812108]
 [ 0.4728199 ]
 [ 0.39843595]
 [ 1.30937693]]
l1
[[ 0.39218877]
 [ 0.61605097]
 [ 0.59831182]
 [ 0.78740888]]
l1_error
[[-0.39218877]
 [-0.61605097]
 [ 0.40168818]
 [ 0.21259112]]
sig
[[ 0.23837674]
 [ 0.23653217]
 [ 0.24033479]
 [ 0.16739614]]
l1_delta
[[-0.09348868]
 [-0.14571587]
 [ 0.09653964]
 [ 0.03558693]]
tmp
[[ 0.13212658]
 [-0.11012894]
 [-0.10707798]]
Output After Training:
[[ 0.39218877]
 [ 0.61605097]
 [ 0.59831182]
 [ 0.78740888]]
[[ 0.96868361]
 [ 0.80081204]
 [-0.54519906]]
