In [1]:
import pyCalc as p
import numpy as np
hop = p.var("constant",np.array([[1,2], [3,4]], dtype = float))
clop = p.var("independent", np.array([2,2]))
glop = p.var("")
glop.f(hop,clop,"*")
chlop = p.var("")
chlop.f(glop, hop, "+")
chlop.value(dict([(clop,np.array([[1,2], [3,4]], dtype = float))]))


4
(2, array([[ 1.,  2.],
       [ 3.,  4.]]))
alive
finding where
here
here
here
[[ 1.  3.]
 [ 2.  4.]]
here
[[ 5.]]
here
[[ 1.  3.]
 [ 2.  4.]]


Exception ignored in: 'pyCalc.cPrintM'
Traceback (most recent call last):
  File "eigency/conversions.pyx", line 13, in eigency.conversions.ndarray_double_F (eigency/conversions.cpp:2621)
ValueError: Cannot create cython.array from NULL pointer


array([[ 5.]])