In [1]:
import pyCalc as p
import numpy as np
hop = p.var("constant",np.array([[1,2], [3,4]], dtype = float))
clop = p.var("independent", np.array([2,2]))
glop = p.var("")
glop.f(hop,clop,"*")
chlop = p.var("")
chlop.f(glop, hop, "+")



[[ 1.  2.]
 [ 3.  4.]]


In [2]:
glop.value(dict([(clop,np.array([[1,2], [3,4]], dtype = float))]))

received
[[ 1.  3.]
 [ 2.  4.]]
used
[[ 1.  2.]
 [ 3.  4.]]
[[ 1.  2.]
 [ 3.  4.]]


array([[  7.,  10.],
       [ 15.,  22.]])

In [3]:
chlop.value(dict([(clop,np.array([[1,2], [3,4]], dtype = float))]))

[[ 1.  2.]
 [ 3.  4.]]


array([[  8.,  12.],
       [ 18.,  26.]])

In [4]:
def getChlopped(jim):
    hop = p.var("constant",np.array([[1,2], [3,4]], dtype = float))
    glop = p.var("")
    glop.f(hop,jim,"*")
    chlop = p.var("")
    chlop.f(glop, hop, "+")
    return chlop

In [ ]:
aaaa = p.var("independent", np.array([2,2]))
g = getChlopped(aaaa)
g.value(dict([(clop,np.array([[1,2], [3,4]], dtype = float))]))