In [1]:
import numpy as np
import pyCalc as p
import random
np.random.seed(1)

xs = p.var("constant", np.array([1,2,3], dtype=float))

ys = p.var("constant",np.array([ [1,2,3],[1,2,3],[1,2,3]]                           
                               , dtype= float))


In [2]:
h = p.function(xs,ys,'*')

In [3]:
h.value()

array([[  6.,  12.,  18.]])

In [4]:
type(h)

pyCalc.var

In [5]:
type(h) == p.var

True

In [6]:
type("ho")

str

In [7]:
type('h')==str

True

In [8]:
h.T().value()

array([[  6.],
       [ 12.],
       [ 18.]])

In [9]:
ch = p.function(h.T(), "unary_pow", 2)

In [10]:
ch.value()

array([[  36.],
       [ 144.],
       [ 324.]])

In [19]:
xs = p.var("constant", np.array([1,2,3], dtype=float))

ys = p.var("constant",np.array([ [1,2,3],[1,2,3],[1,2,3]]                           
                               , dtype= float))
hlp = p.function(ys,xs, "rowwise*")
tmp = p.function(hlp, "rowsum")
print(hlp.value())
print(tmp.value())
glop = p.function(xs, ys, '*')
print(glop.T().value())

[[ 1.  4.  9.]
 [ 1.  4.  9.]
 [ 1.  4.  9.]]
[[ 14.]
 [ 14.]
 [ 14.]]
[[  6.]
 [ 12.]
 [ 18.]]
