In [1]:
import pyCalc as p
import numpy as np
c = p.var("constant",np.array([[1,1,1,1],
                               [0,1,0,1],
                               [0,0,1,1]]                           
                               , dtype= float).T)
x = p.var("independent", np.array([2,2]))
xc = p.var("")
xc.f(x,c, "*")
xmc = p.var("")
xmc.sf(xc, "sigmoid")
weights =np.array([[-0.43812108],
 [ 0.91094098],
 [0.83655703]], dtype = float).T

In [2]:
c.value(dict([(x,weights)]))

array([[ 1.,  1.,  1.,  1.],
       [ 0.,  1.,  0.,  1.],
       [ 0.,  0.,  1.,  1.]])

In [3]:
x.value(dict([(x,weights)]))

array([[-0.43812108,  0.91094098,  0.83655703]])

In [ ]:
xmc.value(dict([(x,weights)]))

In [5]:
xmcx.value(dict([(x,np.array([[2,4], [6,8]], dtype = float))]))

array([[  46.],
       [ 102.]])

In [6]:
xx = p.var("independent", np.array([1,4]))

In [7]:
xx.value(dict([(xx,np.array([[1,2,3,4]], dtype = float).T)]))

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.]])

In [ ]:
xs = p.var("constant",np.array([[0,1,0,1],
                               [1,0,1,0],
                               [0,1,1,0]]                           
                               , dtype= float).T)
tmp = p.var("function")
tmp.sf(xs, "rowwise")
print(xs.value(dict([(x,np.array([[1,2], [3,4]], dtype = float))])))

print(tmp.value(dict([(x,np.array([[1,2], [3,4]], dtype = float))])))